[package]
name = "csvgen"
version = "0.1.0"
authors = ["joppich <joppich@bricknet.de>"]
description = "small utility to create mock-csvfiles."
license = "BSD-3-Clause"
crate-type = ["bin"]

[dependencies]
clap = "2.30.0"
time = ""
rand = ""